
export const cars = {
    'Audi': {
        'model': 'A6',
        'year': '2015',
        'transmission': 'Автоматична',
        'fuel': 'Дизел',
        'engine': '3.0 320',
        'seats': '5',
        'doors': '4',
        'price': '60',
        'img1': './imgs/car-audi-a6.jpg',
        'img2': './imgs/car-audi-a6-2.jpg',
        'img3': './imgs/car-audi-a6-3.jpg',
    },
    'Mercedes': {
        'model': 'C Class',
        'year': '2020',
        'transmission': 'Автоматична',
        'fuel': 'Бензин',
        'engine': '2.0 258',
        'seats': '5',
        'doors': '4',
        'price': '55',
        'img1': './imgs/car-mercedes-c.webp',
        'img2': './imgs/car-mercedes-c-2.jpg',
        'img3': './imgs/car-mercedes-c-3.jpg',
    },
    'Opel ': {
        'model': 'Insignia',
        'year': '2021',
        'transmission': 'Автоматична',
        'fuel': 'Дизел',
        'engine': '2.0 174',
        'seats': '5',
        'doors': '4',
        'price': '45',
        'img1': './imgs/car-opel-insignia.jpg',
        'img2': './imgs/car-opel-insignia-2.jpg',
        'img3': './imgs/car-opel-insignia-3.jpg',
    },
    'Suzuki': {
        'model': 'Vitara',
        'year': '2019',
        'transmission': 'Ръчна',
        'fuel': 'Бензин',
        'engine': '1.4 140',
        'seats': '5',
        'doors': '4',
        'price': '42',
        'img1': './imgs/car-suzuki.jpg',
        'img2': './imgs/car-suzuki-2.jpg',
        'img3': './imgs/car-suzuki-3.jpg',
    },
    'Toyota ': {
        'model': 'Rav4',
        'year': '2015',
        'transmission': 'Автоматик',
        'fuel': 'Бензин',
        'engine': '2.5 176',
        'seats': '5',
        'doors': '4',
        'price': '40',
        'img1': './imgs/car-toyota-rav4.jpg',
        'img2': './imgs/car-toyota-rav4-2.jpg',
        'img3': './imgs/car-toyota-rav4-3.jpg',
    },
    'Renault': {
        'model': 'Zoe',
        'year': '2021',
        'transmission': 'Автоматична',
        'fuel': 'Ток',
        'engine': '52 kWh',
        'seats': '5',
        'doors': '4',
        'price': '30',
        'img1': './imgs/car-renault-zoe.jpg',
        'img2': './imgs/car-renault-zoe-2.jpg',
        'img3': './imgs/car-renault-zoe-3.jpg',
    },
    'Hyundai': {
        'model': 'i30',
        'year': '2020',
        'transmission': 'Ръчна',
        'fuel': 'Бензин',
        'engine': '1.5 110',
        'seats': '5',
        'doors': '4',
        'price': '25',
        'img1': './imgs/car-hyundai.jpg',
        'img2': './imgs/car-hyundai-2.jpg',
        'img3': './imgs/car-hyundai-3.webp',
    },
    'Toyota': {
        'model': 'Yaris',
        'year': '2020',
        'transmission': 'Автоматична',
        'fuel': 'Бензин',
        'engine': '1.5 120',
        'seats': '5',
        'doors': '2',
        'price': '22',
        'img1': './imgs/car-toyota-yaris.jpg',
        'img2': './imgs/car-toyota-yaris-2.jpg',
        'img3': './imgs/car-toyota-yaris-3.jpg',
    },
    'VW': {
        'model': 'Golf',
        'year': '2019',
        'transmission': 'Автоматична',
        'fuel': 'Дизел',
        'engine': '1.6 115',
        'seats': '5',
        'doors': '4',
        'price': '25',
        'img1': './imgs/car-golf.jpg',
        'img2': './imgs/car-golf-2.jpg',
        'img3': './imgs/car-golf-3.webp',
    },
    'Peugeot': {
        'model': '208',
        'year': '2020',
        'transmission': 'Ръчна',
        'fuel': 'Бензин',
        'engine': '1.2 130',
        'seats': '5',
        'doors': '4',
        'price': '25',
        'img1': './imgs/car-peugeot.webp',
        'img2': './imgs/car-peugeot-2.jpg',
        'img3': './imgs/car-peugeot-3.jpg',
    },
    'Opel': {
        'model': 'Astra',
        'year': '2014',
        'transmission': 'Автоматична',
        'fuel': 'Бензин',
        'engine': '1.6 115',
        'seats': '5',
        'doors': '4',
        'price': '20',
        'img1': './imgs/car-opel-astra.jpg',
        'img2': './imgs/car-opel-astra-2.jpg',
        'img3': './imgs/car-opel-astra-3.jpg',
    },
    'Skoda': {
        'model': 'Fabia',
        'year': '2015',
        'transmission': 'Ръчна',
        'fuel': 'Дизел',
        'engine': '1.4 105',
        'seats': '5',
        'doors': '4',
        'price': '20',
        'img1': './imgs/car-skoda-fabia.webp',
        'img2': './imgs/car-skoda-fabia-2.jpg',
        'img3': './imgs/car-skoda-fabia-3.jpg',
    },
    
    
}

